module html {
	interface [
		Conditional=WEBCL,
		HasIndexGetter
	] WebCLPlatformIDList {
        readonly attribute unsigned long length;	
		WebCLPlatformID item(in [IsIndex] unsigned long index);
	};
}